name: linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          python run-clang-format.py -r src
          python run-clang-format.py -r test --exclude test/catch
